CREATE DATABASE IF NOT EXISTS expenses_db;
USE expenses_db;

CREATE TABLE IF NOT EXISTS gastos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  centroCosto VARCHAR(100) NOT NULL,
  origenFondos VARCHAR(50) NOT NULL,
  monto INT NOT NULL,
  lugarCompra VARCHAR(50) NOT NULL,
  fechaCreacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);